### ISSUE TITLE
Kali linux unrecognized

### ISSUE THREAD

**Issue by srinivasans13** [supr4s/VPS-web-hacking-tools#2]
I face this error while executing this script 

[ENVIRONMENT] Packages required installation in progress ...
O.S unrecognized
End of the script

uname -a 
Linux kali 5.7.0-kali1-amd64 #1 SMP Debian 5.7.6-1kali2 (2020-07-01) x86_64 GNU/Linux

**Comment by supr4s** [comment]
Hello,

As stated in the documentation, there are only two recognized operating systems : 

```
O.S supported :

Ubuntu 20.04 x64
Debian 10 x64
```

**Comment by mdsabbirkhan** [comment]
same issues ,how to solve ?

[ENVIRONMENT] Packages required installation in progress ...
O.S unrecognized
End of the script

Linux kali 5.10.0-kali9-amd64 #1 SMP Debian 5.10.46-4kali1 (2021-08-09) x86_64 GNU/Linux

**Comment by supr4s** [comment]
Added in the last release :)
